### PR TITLE
Update user-agents.json

### PR DESCRIPTION
**Pull request by malarvili92**

### CODE REVIEW

**Comment by johnspurlock** [comment]
Thanks - can you provide example user agents for iOS and Android?  And a product url pointing to the app or service that this is for?

**Comment by malarvili92** [comment]
Hi,


The details of our SYOK user agent as per listed below:












*{    "user_agents": ["^Syok.+[Aa]ndroid"],    "app": "Syok",    "device":
"phone",    "os": "android"},{    "user_agents": ["^Syok.+iOS"],    "app":
"Syok",    "device": "phone",    "os": "ios"}*


Megaphone :
https://cms.megaphone.fm/organizations/daddcfcc-c6c2-11ed-883d-2fed0ee894b3/dashboard

We're using megaphone podcast provider to host our podcasts


From,

Malar,

Technical team,

*SYOK product*
Astro Radio Sdn Bhd (403472-D)
All Asia Broadcast Centre, Technology Park Malaysia
Lebuhraya Puchong-Sg. Besi, Bukit Jalil, 57000 Kuala Lumpur.

**Comment by malarvili92** [comment]
Hi,

May I know do we need to include windows or mobile browsers for the users
who are listening to the podcasts?

Regards,

Malar,

Technical team,

*SYOK product*
Astro Radio Sdn Bhd (403472-D)
All Asia Broadcast Centre, Technology Park Malaysia
Lebuhraya Puchong-Sg. Besi, Bukit Jalil, 57000 Kuala Lumpur.

**Comment by johnspurlock** [comment]
Hi there - unfortunately none of those are answers to my questions.  I'm going to assume this is for the product at `https://syok.my`

I downloaded the SYOK app on iOS and it does not appear to be a general purpose podcast player, which is typically what this user agent database is for.  Is there a way to add a podcast to the app using an RSS feed?  I couldn't find it.

The user agent this app sends when downloading is: `SYOK/965 CFNetwork/1406.0.4 Darwin/22.4.0`
and does not set a user-agent when streaming, which is unfortunate since that is the default playback mode of the app.

Added to the public list of apps that do not set a streaming user agent: https://docs.google.com/spreadsheets/d/1YKQgt7xwLSdHmgtZew1TVD_RqzuA9W0ec0ab9BF9E0c/edit?usp=sharing

**Comment by malarvili92** [comment]
Hi, 
Apologies for assuming wrongly. 
we're using podcast provider[Megaphone] to stream our podcast. Now we having issue in Megaphone reporting side at where SYOK user agents not found. Our current flow is adding the podcast to the app via API not using RSS. 

Is there any way we can get those user agent : `SYOK/965 CFNetwork/1406.0.4 Darwin/22.4.0` in the OPAWG list?
Thanks!

**Comment by johnspurlock** [comment]
ah ok

can you provide an example Android user agent string as well?  The one I found above was from iOS

**Comment by malarvili92** [comment]
Apologies for delayed in response.
Our mobile developer provided this useragent from android. Could you assist to include those useragents in the OPAWG list?
```
{
      "name": "SYOK",
      "pattern": "^SYOK.+([Aa]ndroid|iOS|Darwin)",
      "examples": [
        "SYOK/965 CFNetwork/1406.0.4 Darwin/22.4.0"
      ]
    }
```

Let me know if you need any further details?
Thanks you.

**Comment by johnspurlock** [comment]
`SYOK/965 CFNetwork/1406.0.4 Darwin/22.4.0` is the found iOS user agent string I listed above, you still have not provided an example Android user agent string (an example user-agent header value sent from your Android app).

We'll need one to add to the "examples" array

**Comment by malarvili92** [comment]
UserAgent(android=Mozilla/5.0 (Linux; Android 7.0; SM-G930V Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.125 Mobile Safari/537.36)
Is this correct?

**Comment by johnspurlock** [comment]
No, that's a browser.  Your Android app codebase should contain the user-agent you're sending, or one of your developers should be able to test and see for themselves.

**Comment by malarvili92** [comment]
Our mobile developer having issue to find the user agent, can you provide guidelines how to do it so. Please assist on this.
Thank you!

**Comment by malarvili92** [comment]
we would like to validate this user agent: `my.com.astro.player`

**Comment by johnspurlock** [comment]
Alright this is not really going anywhere productive, I added a pattern based on the one known example.

https://github.com/opawg/user-agents/commit/d3f9c9e4c2180d48f848419960d390a6e2d785f3

If you have an example of the user-agent that your Android app sends (it should include something that identifies your app vs others), please let me know.

Also, whoever you are working with that is using this github repo, tell them this repo is obsolete, and should be using user-agents-v2.  I added SYOK to that repo as well.

See the note here for more info: https://github.com/opawg/user-agents#this-is-going-away

**Pull request closed without merging**
