### PR TITLE
Update user-agents.json

### PR DESCRIPTION
**Pull request by MacMark**
Add detection for radio.net Apple apps

### CODE REVIEW

**Comment by johnspurlock** [comment]
Can you update the PR to include `"examples"` and `"info_url"`?

**Comment by MacMark** [comment]
Thanks for your hint, i added examples and info url to that entry.

**Comment by johnspurlock** [comment]
Sorry, one more: make sure you encode `\` as `\\` inside json strings (otherwise it's invalid json)

**Comment by MacMark** [comment]
Thanks for your hint, i fixed it. The GitHub preview shows the error too. I should have seen it by myself.

**Comment by johnspurlock** [comment]
Thanks again!

**Pull request merged**
