### PR TITLE
Update Spotify bot user agent

### PR DESCRIPTION
**Pull request by vparpoil**
To exactly match Spotify/1.0 bot
See [this issue ](https://github.com/opawg/user-agents/issues/36)

### CODE REVIEW

**Comment by jamescridland** [comment]
@tomrossi7 - I'm seeing Spotify/1.0 is used to grab the RSS, and also used precisely once for audio, to grab the audio for its own cache. I think it a) fair to claim it's a bot; and b) even if not, this probably doesn't make this pull request invalid, given it's merely tightening up the useragent here and not changing an earlier decision that this is a bot, so I will merge this pull request.

If anyone has passthrough, though, and can clarify useragents when used in a passthrough situation, I'd be grateful.

**Comment by jamescridland** [comment]
Further... I've heard from someone with passthrough. Useragents when used with passthrough are things like:

`Spotify/8.4.94 Android/26 (SM-G950F)`
`Spotify/8.4.93 iOS/12.1.4 (iPhone8,1)`

...and therefore I'm confident that this is a bot. Thanks for the comment, though.

**Comment by tomrossi7** [comment]
Thanks @jamescridland I just compared to our database and can confirm!

**Comment by pierrocknroll** [comment]
The Json file seems to be invalid since this change

**Pull request merged**
